In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("diabetes.csv",index_col=None)
dataset

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1


In [3]:
X=dataset[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age',]]
Y=dataset['Outcome']

In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
X_train

array([[ 0.90832902,  0.91569367,  0.44912368, ...,  0.37852648,
         0.67740401,  1.69955804],
       [ 0.03644676, -0.75182191, -0.47230103, ..., -0.50667229,
        -0.07049698, -0.96569189],
       [-1.12606292,  1.38763205,  1.06340683, ...,  2.54094063,
        -0.11855487, -0.88240283],
       ...,
       [ 0.03644676, -0.84620959, -0.21634972, ..., -0.94927168,
        -0.95656442, -1.04898095],
       [ 2.0708387 , -1.12937261,  0.24436264, ..., -0.26640405,
        -0.50001442,  0.11706589],
       [ 0.32707418,  0.47521786,  0.65388473, ..., -4.07275877,
         0.52121586,  2.94889395]])

In [7]:
X_test

array([[-0.8354355 ,  2.45735903,  0.34674316, ...,  1.35224513,
         2.78594417, -0.96569189],
       [-0.54480808, -0.43719633,  0.24436264, ...,  0.17619533,
        -0.1876381 , -0.88240283],
       [ 0.03644676, -1.41253563, -0.36992051, ...,  0.22677812,
        -0.22668514, -0.71582471],
       ...,
       [ 0.03644676,  0.66399321,  0.85864578, ...,  1.4913478 ,
         0.53623395, -0.96569189],
       [-0.25418066, -0.15403331,  0.24436264, ..., -0.74694053,
        -1.07971278, -0.79911377],
       [-0.8354355 , -0.43719633,  0.14198211, ..., -0.17788417,
         1.06487079, -0.79911377]])

In [8]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(n_components = 5)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_
pca
#op=pca.get_feature_names_out(input_features=None)
#op

PCA(n_components=5)

In [9]:
n_components = 5
selected_features = X.columns[:n_components]
selected_features

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin'], dtype='object')

In [10]:
X_train

array([[ 1.55903001,  1.61914081,  0.41777967,  0.38279528, -0.22490718],
       [-1.06486934, -0.73790078, -0.33607421,  0.3381568 , -0.37242706],
       [ 4.49192558, -2.07048749,  0.90191999, -2.31499387, -0.07115083],
       ...,
       [-1.51010987, -0.62311527, -0.68437341, -0.37296695, -0.57050955],
       [-1.36750774,  1.67116765, -0.80426357,  0.3759464 , -0.76277266],
       [-1.86191417,  3.0680674 ,  1.73287469,  0.92106869, -0.3348298 ]])

In [11]:
X_test

array([[ 2.63746470e+00, -1.10056873e+00,  8.80051738e-01,
         1.52773216e+00,  2.07137301e+00],
       [ 1.39617011e-01, -1.13075325e+00, -6.05248935e-01,
        -1.47116037e-01, -1.09014845e-01],
       [-1.62717184e+00, -3.25528745e-01, -6.43101597e-01,
         4.28487653e-01,  2.19441922e-01],
       [ 8.26885878e-01,  1.37478760e+00,  1.44209481e+00,
        -2.65956396e-01, -5.90373357e-02],
       [-1.49633607e+00, -4.05079176e-01,  5.97353763e-01,
         7.09005891e-01,  1.02261592e+00],
       [-1.31121931e+00, -1.04801692e+00, -7.58363193e-01,
        -7.53247990e-03, -1.39972797e-01],
       [ 1.83813547e+00,  6.39133976e-01,  6.09677408e-01,
         6.62087831e-01, -6.35663110e-01],
       [ 2.24793844e+00,  9.67076689e-01,  1.34064209e+00,
         1.11490060e+00,  8.86561113e-01],
       [ 1.28808870e+00, -1.54439650e+00,  2.38942671e+00,
         2.26870742e+00, -2.33852766e-01],
       [ 1.04361107e+00,  1.01633999e+00, -4.46923769e-01,
        -2.10133178e-01

In [12]:
explained_variance

array([0.2595475 , 0.22020622, 0.12734819, 0.11057783, 0.09403196])

In [13]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [14]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [15]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[93, 14],
       [21, 26]], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
        
Accuracy=accuracy_score(y_test, y_pred)
report=classification_report(y_test, y_pred)
Accuracy

0.7727272727272727

In [17]:
import pickle
filename="Finalized_model_PCA_LR.sav"

In [18]:
pickle.dump(classifier,open(filename,'wb'))

In [19]:
loaded_module=pickle.load(open("Finalized_model_PCA_LR.sav",'rb'))

In [20]:
preinput=([[6,148,72,35,0]])    #preinpu=sc.fittransform([[
preinput

[[6, 148, 72, 35, 0]]

In [21]:
result1=loaded_module.predict(preinput)
result1

array([1], dtype=int64)